### ISSUE TITLE
翻訳されていないスライドが1つあります

### ISSUE THREAD

**Issue by trufae** [radareorg/r2jp#13]
https://github.com/radareorg/r2jp/blob/master/r2AvTokyo-talk-JP.pdf

<img width="1131" alt="screen shot 2017-11-29 at 15 12 50" src="https://user-images.githubusercontent.com/6431515/33379527-ba8cac44-d518-11e7-8aaf-581a420e7567.png">

**Comment by unixfreaxjp** [comment]
英文の方が分り易いから翻訳されていなかった、全部無理やりカタカナで引っ張りますともっとの意味が分らなくなってません？

**Comment by tessyjp** [comment]
このP11は日本語あてられそうなので、暇見てやりましょうか？
見直していてP29の()内も日本語にしてもいいかも。

<img width="1019" alt="r2jp_p29" src="https://user-images.githubusercontent.com/614072/33596726-0dece13a-d9e0-11e7-9fbd-d14bf7b2de4f.png">

**Comment by unixfreaxjp** [comment]
まだメインストリームになってないサブプロジェクトも書いてあるからね、、

**Comment by radare** [comment]
Okok , closing then :)

thanks!
